### ISSUE TITLE
new rule: `var` variable is never modified

### ISSUE THREAD

**Issue by nektro** [nektro/ziglint#7]
```zig
const std = @import("std");

pub fn main() void {
    var a: u32 = 5;

    std.log.info("{d}", .{a});
}
```
```
./test.zig:4:9: local variable 'a' is never modified, should be const

**Comment by nektro** [comment]
operators that modify value
- `=`
- `+=`
- `+|=`
- `-=`
- `-%=`
- `-|=`
- `*=`
- `*%=`
- `*|=`
- `/=`
- `%=`
- `<<=`
- `<<|=`
- `>>=`
- `&=`
- `|=`
- `^=`

**Comment by nektro** [comment]
also want to include `&` since a var might be passed a `&argument` and then not modified inside the function body it was defined, but rather inside the function its passed to.

**Comment by nektro** [comment]
hm functions and methods complicate the feasibility of this a lot

**Comment by paperclover** [comment]
this is now a compiler error
